name=@extname@
description=Exports a minimal ELF file containing DWARF function symbols derived from Ghidra's analysis. Intended for use with GDB's symbol-file command to enable stack unwinding on esoteric targets such as emulator GDB stubs.
author=aldelaro5
createdOn=2026-05-17
version=@extversion@
